<center><img SRC="OIP.jpg"/></center>
<center><h1 style="color: #483D8B"> Analisis de datos</h1></center>
<center><h2 style="color: #008B8B"> Universidad Castro Carazo</h2></center>
<center><h6 style="color: #008B8B"> II Cuatrimestre 2022</h6></center>
</br>
</br>
<p>Explicación del proyecto que se este presentando, para alinear el texto se debe de usar el text-aling:center.</p>

<p>Para ingresar un link se usa: a href="htl">Nombre del link- y cierro a </p>
<a href="https://www.w3schools.com/cssref/css_colors.asp">Pagina para Stylos </a>
<p>Para usar negrita style="font-weight:bold" </p>
<p style="font-weight:bold"> Prueba en negrita</p>

<h2 Style="color:#483D8B">1. Carga y estandarización de los archivos de datos </h2>
<p style ="font-weight:bold"> ¿Que se en este apartado?</p>
<ol>
    <li> Importar las librerias a utilizar</li>
    <li> Importar los <p style="font-wight:bold">set de datos</p>      (xlsx,csv,txt, oracle</li>
    <li> Revisión de las columnas del set de datos</li>
    <li> Si tenemos mas de un set, unirlo en un unico dataframe</li>
</ol>

<h5 style="color: #008B8B">1.1 Importar las librerias a utilizar</h5>

In [1]:
# Se coloca una explicación de que se cargaran las librerias para el analisis en curso
import pandas as pd #para los manejo de los datos -Dataframe-.
import numpy as np # Para menejo de estructuras de datos -Listas-.
import matplotlib.pyplot as plt # Para la creación de los graficos.
# Se le da correr para que cargue las librerias verificando la bolita negra.

<h5 style="color: #008B8B">1.2 Importar el set de datos</h5>
<a hre="https://archive.ics.uci.edu/ml/datasets/Automobile">Fuente de datos</a>

In [2]:
# Importante si el set de datos no trae nombres de columnas. Se debe de crear la lista con los nombre como una variable.
cols = ["symboling", "normalized", "make", "fuel", "aspiration", "doors",
"style", "wheels", "engine", "base", "length", "width", "heingt",
"curb", "engineType", "Cylinders", "engine-size", "system", "bore", "stroke",
"compression", "horsepower", "peak", "City", "Higway", "price"]
#Se cargan los set de datos en la memoria del la PC
df_autos1=pd.read_csv("autos1.csv",names=cols)
df_autos2=pd.read_csv("autos.csv",names=cols)

<h5 style="color: #008B8B"> Revisión y Validación de las varialbles</h5> 
<center><p>Este proceso de revision permite identificar viariables o datos que deben ser analizados de manera independiente ya que no concuerdan con el rango de información a contener.</p>

In [3]:
df_autos1

,symboling,normalized,make,fuel,aspiration,doors,style,wheels,engine,base,...,engine-size,system,bore,stroke,compression,horsepower,peak,City,Higway,price
0,0,106,nissan,gas,std,four,sedan,fwd,front,97.2,...,120,2bbl,3.33,3.47,8.5,97,5200,27,34,9549
1,0,128,nissan,gas,std,four,sedan,fwd,front,100.4,...,181,mpfi,3.43,3.27,9.0,152,5200,17,22,13499
2,0,108,nissan,gas,std,four,wagon,fwd,front,100.4,...,181,mpfi,3.43,3.27,9.0,152,5200,17,22,14399
3,0,108,nissan,gas,std,four,sedan,fwd,front,100.4,...,181,mpfi,3.43,3.27,9.0,152,5200,19,25,13499
4,3,194,nissan,gas,std,two,hatchback,rwd,front,91.3,...,181,mpfi,3.43,3.27,9.0,160,5200,19,25,17199
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92,0,?,volkswagen,diesel,turbo,four,sedan,fwd,front,100.4,...,97,idi,3.01,3.40,23.0,68,4500,33,38,13845
93,0,?,volkswagen,gas,std,four,wagon,fwd,front,100.4,...,109,mpfi,3.19,3.40,9.0,88,5500,25,31,12290
94,-2,103,volvo,gas,std,four,sedan,rwd,front,104.3,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,12940
95,-1,74,volvo,gas,std,four,wagon,rwd,front,104.3,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,13415
96,-2,103,volvo,gas,std,four,sedan,rwd,front,104.3,...,141,mpfi,3.78,3.15,9.5,114,5400,24,28,15985

In [4]:
df_autos2

,symboling,normalized,make,fuel,aspiration,doors,style,wheels,engine,base,...,engine-size,system,bore,stroke,compression,horsepower,peak,City,Higway,price
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
192,0,?,volkswagen,diesel,turbo,four,sedan,fwd,front,100.4,...,97,idi,3.01,3.40,23.0,68,4500,33,38,13845
193,0,?,volkswagen,gas,std,four,wagon,fwd,front,100.4,...,109,mpfi,3.19,3.40,9.0,88,5500,25,31,12290
194,-2,103,volvo,gas,std,four,sedan,rwd,front,104.3,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,12940
195,-1,74,volvo,gas,std,four,wagon,rwd,front,104.3,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,13415
196,-2,103,volvo,gas,std,four,sedan,rwd,front,104.3,...,141,mpfi,3.78,3.15,9.5,114,5400,24,28,15985

In [5]:
#Para conocer la cantidad de columnas y sus observaciones se utiliza el siguiente codigo: Siendo su primer dato cantidad de observaciones y segundo sus columnas
df_autos1.shape

(97, 26)

In [6]:
df_autos2.shape

(197, 26)

In [7]:
#Para conocer los nombres de las las columnas se utiliza
df_autos1.columns

Index(['symboling', 'normalized', 'make', 'fuel', 'aspiration', 'doors',
       'style', 'wheels', 'engine', 'base', 'length', 'width', 'heingt',
       'curb', 'engineType', 'Cylinders', 'engine-size', 'system', 'bore',
       'stroke', 'compression', 'horsepower', 'peak', 'City', 'Higway',
       'price'],
      dtype='object')

In [8]:
df_autos2.columns

Index(['symboling', 'normalized', 'make', 'fuel', 'aspiration', 'doors',
       'style', 'wheels', 'engine', 'base', 'length', 'width', 'heingt',
       'curb', 'engineType', 'Cylinders', 'engine-size', 'system', 'bore',
       'stroke', 'compression', 'horsepower', 'peak', 'City', 'Higway',
       'price'],
      dtype='object')

In [9]:
df_autos1.head(15)

,symboling,normalized,make,fuel,aspiration,doors,style,wheels,engine,base,...,engine-size,system,bore,stroke,compression,horsepower,peak,City,Higway,price
0,0,106,nissan,gas,std,four,sedan,fwd,front,97.2,...,120,2bbl,3.33,3.47,8.5,97,5200,27,34,9549
1,0,128,nissan,gas,std,four,sedan,fwd,front,100.4,...,181,mpfi,3.43,3.27,9.0,152,5200,17,22,13499
2,0,108,nissan,gas,std,four,wagon,fwd,front,100.4,...,181,mpfi,3.43,3.27,9.0,152,5200,17,22,14399
3,0,108,nissan,gas,std,four,sedan,fwd,front,100.4,...,181,mpfi,3.43,3.27,9.0,152,5200,19,25,13499
4,3,194,nissan,gas,std,two,hatchback,rwd,front,91.3,...,181,mpfi,3.43,3.27,9.0,160,5200,19,25,17199
5,3,194,nissan,gas,turbo,two,hatchback,rwd,front,91.3,...,181,mpfi,3.43,3.27,7.8,200,5200,17,23,19699
6,1,231,nissan,gas,std,two,hatchback,rwd,front,99.2,...,181,mpfi,3.43,3.27,9.0,160,5200,19,25,18399
7,0,161,peugot,gas,std,four,sedan,rwd,front,107.9,...,120,mpfi,3.46,3.19,8.4,97,5000,19,24,11900
8,0,161,peugot,diesel,turbo,four,sedan,rwd,front,107.9,...,152,idi,3.70,3.52,21.0,95,4150,28,33,13200
9,0,?,peugot,gas,std,four,wagon,rwd,front,114.2,...,120,mpfi,3.46,3.19,8.4,97,5000,19,24,12440
10,0,?,peugot,diesel,turbo,four,wagon,rwd,front,114.2,...,152,idi,3.70,3.52,21.0,95,4150,25,25,13860
11,0,161,peugot,gas,std,four,sedan,rwd,front,107.9,...,120,mpfi,3.46,2.19,8.4,95,5000,19,24,15580
12,0,161,peugot,diesel,turbo,four,sedan,rwd,front,107.9,...,152,idi,3.70,3.52,21.0,95,4150,28,33,16900
13,0,?,peugot,gas,std,four,wagon,rwd,front,114.2,...,120,mpfi,3.46,2.19,8.4,95,5000,19,24,16695
14,0,?,peugot,diesel,turbo,four,wagon,rwd,front,114.2,...,152,idi,3.70,3.52,21.0,95,4150,25,25,17075

In [10]:
df_autos1.tail(15)

,symboling,normalized,make,fuel,aspiration,doors,style,wheels,engine,base,...,engine-size,system,bore,stroke,compression,horsepower,peak,City,Higway,price
82,2,122,volkswagen,diesel,std,two,sedan,fwd,front,97.3,...,97,idi,3.01,3.40,23.0,52,4800,37,46,7775
83,2,122,volkswagen,gas,std,two,sedan,fwd,front,97.3,...,109,mpfi,3.19,3.40,9.0,85,5250,27,34,7975
84,2,94,volkswagen,diesel,std,four,sedan,fwd,front,97.3,...,97,idi,3.01,3.40,23.0,52,4800,37,46,7995
85,2,94,volkswagen,gas,std,four,sedan,fwd,front,97.3,...,109,mpfi,3.19,3.40,9.0,85,5250,27,34,8195
86,2,94,volkswagen,gas,std,four,sedan,fwd,front,97.3,...,109,mpfi,3.19,3.40,9.0,85,5250,27,34,8495
87,2,94,volkswagen,diesel,turbo,four,sedan,fwd,front,97.3,...,97,idi,3.01,3.40,23.0,68,4500,37,42,9495
88,2,94,volkswagen,gas,std,four,sedan,fwd,front,97.3,...,109,mpfi,3.19,3.40,10.0,100,5500,26,32,9995
89,3,?,volkswagen,gas,std,two,convertible,fwd,front,94.5,...,109,mpfi,3.19,3.40,8.5,90,5500,24,29,11595
90,3,256,volkswagen,gas,std,two,hatchback,fwd,front,94.5,...,109,mpfi,3.19,3.40,8.5,90,5500,24,29,9980
91,0,?,volkswagen,gas,std,four,sedan,fwd,front,100.4,...,136,mpfi,3.19,3.40,8.5,110,5500,19,24,13295
92,0,?,volkswagen,diesel,turbo,four,sedan,fwd,front,100.4,...,97,idi,3.01,3.40,23.0,68,4500,33,38,13845
93,0,?,volkswagen,gas,std,four,wagon,fwd,front,100.4,...,109,mpfi,3.19,3.40,9.0,88,5500,25,31,12290
94,-2,103,volvo,gas,std,four,sedan,rwd,front,104.3,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,12940
95,-1,74,volvo,gas,std,four,wagon,rwd,front,104.3,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,13415
96,-2,103,volvo,gas,std,four,sedan,rwd,front,104.3,...,141,mpfi,3.78,3.15,9.5,114,5400,24,28,15985

In [11]:
df_autos1.describe()

,symboling,base,length,width,heingt,curb,engine-size,bore,stroke,compression,City,Higway
count,97.000000,97.000000,97.000000,97.000000,97.000000,97.000000,97.000000,97.000000,97.000000,97.000000,97.000000,97.000000
mean,0.855670,98.823711,175.208247,65.872165,54.194845,2587.175258,125.432990,3.388969,3.169381,10.570206,25.185567,30.814433
std,1.314896,5.332170,10.064062,1.655719,2.416755,412.305914,29.560992,0.264412,0.352691,4.373831,5.470241,5.784912
min,-2.000000,89.500000,156.900000,63.400000,49.700000,1918.000000,90.000000,2.540000,2.070000,7.000000,17.000000,22.000000
25%,0.000000,95.700000,168.900000,64.400000,52.500000,2261.000000,98.000000,3.190000,3.030000,9.000000,20.000000,25.000000
50%,0.000000,97.300000,173.500000,65.600000,54.500000,2535.000000,120.000000,3.430000,3.230000,9.000000,25.000000,30.000000
75%,2.000000,100.400000,183.500000,66.600000,56.000000,2975.000000,146.000000,3.620000,3.400000,9.400000,28.000000,34.000000
max,3.000000,114.200000,198.900000,72.300000,59.800000,3485.000000,203.000000,3.940000,3.900000,23.000000,38.000000,47.000000

In [12]:
df_autos1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 97 entries, 0 to 96
Data columns (total 26 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   symboling    97 non-null     int64
 1   normalized   97 non-null     object
 2   make         97 non-null     object
 3   fuel         97 non-null     object
 4   aspiration   97 non-null     object
 5   doors        97 non-null     object
 6   style        97 non-null     object
 7   wheels       97 non-null     object
 8   engine       97 non-null     object
 9   base         97 non-null     float64
 10  length       97 non-null     float64
 11  width        97 non-null     float64
 12  heingt       97 non-null     float64
 13  curb         97 non-null     int64
 14  engineType   97 non-null     object
 15  Cylinders    97 non-null     object
 16  engine-size  97 non-null     int64
 17  system       97 non-null     object
 18  bore         97 non-null     float64
 19  stroke       97 non-null     float64
 20  compression  97 non-null     float64
 21  horsepower   97 non-null     object
 22  peak         97 non-null     object
 23  City         97 non-null     int64
 24  Higway       97 non-null     int64
 25  price        97 non-null     object
dtypes: float64(7), int64(5), object(14)
memory usage: 19.8+ KB

<h5 style="color: #008B8B">1.4 Unir los ser de datos</h5>

In [13]:
#df_autos1-97 observaciones y 26 columnas
#df_autos2-197 observaciones y 26 columnas


Unionarchivos=[df_autos1,df_autos2]
df_autos=pd.concat(Unionarchivos)
df_autos.shape

(294, 26)

<h2 Style="color:#483D8B">2. Manejo de valores faltantes </h2>
<p style ="font-weight:bold"> ¿Que se en este apartado?</p>
<ol>
    <li> Identificar como se muestran los valores faltantes y estandarizarlos a NaN</li>
    <li> Contar la cantidad de valores NaN (Faltantes)</li>
    <li> Analisis para imputar los valorwa numericos con la media</li>
    <li> Analisis para imputar los caracter con el mas frecuente</li>
    <li> Eliminar filas con valores faltantes</li>
</ol>

<h5 style="color: #008B8B">2.1 Identificar como se muestra los valores faltantes y estandarizalos a NaN</h5>

<p> Valores faltantes</p>
<ol>
    <li>NaN</li>
    <li>" "</li>
    <li>null</li>
    <li>?</li>
    <li>entre otros</li>
</ol>

In [15]:
df_autos.replace("?",np.nan,inplace=True)
df_autos.head(10)

,symboling,normalized,make,fuel,aspiration,doors,style,wheels,engine,base,...,engine-size,system,bore,stroke,compression,horsepower,peak,City,Higway,price
0,0,106,nissan,gas,std,four,sedan,fwd,front,97.2,...,120,2bbl,3.33,3.47,8.5,97,5200,27,34,9549
1,0,128,nissan,gas,std,four,sedan,fwd,front,100.4,...,181,mpfi,3.43,3.27,9.0,152,5200,17,22,13499
2,0,108,nissan,gas,std,four,wagon,fwd,front,100.4,...,181,mpfi,3.43,3.27,9.0,152,5200,17,22,14399
3,0,108,nissan,gas,std,four,sedan,fwd,front,100.4,...,181,mpfi,3.43,3.27,9.0,152,5200,19,25,13499
4,3,194,nissan,gas,std,two,hatchback,rwd,front,91.3,...,181,mpfi,3.43,3.27,9.0,160,5200,19,25,17199
5,3,194,nissan,gas,turbo,two,hatchback,rwd,front,91.3,...,181,mpfi,3.43,3.27,7.8,200,5200,17,23,19699
6,1,231,nissan,gas,std,two,hatchback,rwd,front,99.2,...,181,mpfi,3.43,3.27,9.0,160,5200,19,25,18399
7,0,161,peugot,gas,std,four,sedan,rwd,front,107.9,...,120,mpfi,3.46,3.19,8.4,97,5000,19,24,11900
8,0,161,peugot,diesel,turbo,four,sedan,rwd,front,107.9,...,152,idi,3.7,3.52,21.0,95,4150,28,33,13200
9,0,NaN,peugot,gas,std,four,wagon,rwd,front,114.2,...,120,mpfi,3.46,3.19,8.4,97,5000,19,24,12440

<h5 style="color: #008B8B">Contar los valores faltantes por columna</h5>

In [16]:
valoresperdidos=df_autos.isnull()
valoresperdidos.head(10)

,symboling,normalized,make,fuel,aspiration,doors,style,wheels,engine,base,...,engine-size,system,bore,stroke,compression,horsepower,peak,City,Higway,price
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9,False,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [34]:
for column in valoresperdidos.columns.values.tolist():
    print(column)
    print(valoresperdidos[column].value_counts())
    print("")

symboling
False    294
Name: symboling, dtype: int64

normalized
False    237
True      57
Name: normalized, dtype: int64

make
False    294
Name: make, dtype: int64

fuel
False    294
Name: fuel, dtype: int64

aspiration
False    294
Name: aspiration, dtype: int64

doors
False    292
True       2
Name: doors, dtype: int64

style
False    294
Name: style, dtype: int64

wheels
False    294
Name: wheels, dtype: int64

engine
False    294
Name: engine, dtype: int64

base
False    294
Name: base, dtype: int64

length
False    294
Name: length, dtype: int64

width
False    294
Name: width, dtype: int64

heingt
False    294
Name: heingt, dtype: int64

curb
False    294
Name: curb, dtype: int64

engineType
False    294
Name: engineType, dtype: int64

Cylinders
False    294
Name: Cylinders, dtype: int64

engine-size
False    294
Name: engine-size, dtype: int64

system
False    294
Name: system, dtype: int64

bore
False    290
True       4
Name: bore, dtype: int64

stroke
False    290
True       4
Name: stroke, dtype: int64

compression
False    294
Name: compression, dtype: int64

horsepower
False    290
True       4
Name: horsepower, dtype: int64

peak
False    290
True       4
Name: peak, dtype: int64

City
False    294
Name: City, dtype: int64

Higway
False    294
Name: Higway, dtype: int64

price
False    289
True       5
Name: price, dtype: int64

<h5 style="color: #008B8B">Analisis para imputar datos númericos con la media</h5>

In [31]:
avg_norm=df_autos["price"].astype("float").mean(axis=0)
print("La media es:",avg_norm)

La media es: 12625.910034602077

In [32]:
df_autos["price"].replace(np.nan,12626,inplace=True)
df_autos.head(10)

,symboling,normalized,make,fuel,aspiration,doors,style,wheels,engine,base,...,engine-size,system,bore,stroke,compression,horsepower,peak,City,Higway,price
0,0,106,nissan,gas,std,four,sedan,fwd,front,97.2,...,120,2bbl,3.33,3.47,8.5,97,5200,27,34,9549
1,0,128,nissan,gas,std,four,sedan,fwd,front,100.4,...,181,mpfi,3.43,3.27,9.0,152,5200,17,22,13499
2,0,108,nissan,gas,std,four,wagon,fwd,front,100.4,...,181,mpfi,3.43,3.27,9.0,152,5200,17,22,14399
3,0,108,nissan,gas,std,four,sedan,fwd,front,100.4,...,181,mpfi,3.43,3.27,9.0,152,5200,19,25,13499
4,3,194,nissan,gas,std,two,hatchback,rwd,front,91.3,...,181,mpfi,3.43,3.27,9.0,160,5200,19,25,17199
5,3,194,nissan,gas,turbo,two,hatchback,rwd,front,91.3,...,181,mpfi,3.43,3.27,7.8,200,5200,17,23,19699
6,1,231,nissan,gas,std,two,hatchback,rwd,front,99.2,...,181,mpfi,3.43,3.27,9.0,160,5200,19,25,18399
7,0,161,peugot,gas,std,four,sedan,rwd,front,107.9,...,120,mpfi,3.46,3.19,8.4,97,5000,19,24,11900
8,0,161,peugot,diesel,turbo,four,sedan,rwd,front,107.9,...,152,idi,3.7,3.52,21.0,95,4150,28,33,13200
9,0,122,peugot,gas,std,four,wagon,rwd,front,114.2,...,120,mpfi,3.46,3.19,8.4,97,5000,19,24,12440

<h5 style="color: #008B8B">Analisis para imputar caracteres más frecuentes</h5>

In [35]:
df_autos["doors"].value_counts()

four    167
two     125
Name: doors, dtype: int64

In [36]:
df_autos["doors"].value_counts().idxmax()

'four'

In [37]:
df_autos["doors"].replace(np.nan,"four",inplace=True)

In [38]:
valoresperdidos=df_autos.isnull()
for column in valoresperdidos.columns.values.tolist():
    print(column)
    print(valoresperdidos[column].value_counts())
    print("")

symboling
False    294
Name: symboling, dtype: int64

normalized
False    294
Name: normalized, dtype: int64

make
False    294
Name: make, dtype: int64

fuel
False    294
Name: fuel, dtype: int64

aspiration
False    294
Name: aspiration, dtype: int64

doors
False    294
Name: doors, dtype: int64

style
False    294
Name: style, dtype: int64

wheels
False    294
Name: wheels, dtype: int64

engine
False    294
Name: engine, dtype: int64

base
False    294
Name: base, dtype: int64

length
False    294
Name: length, dtype: int64

width
False    294
Name: width, dtype: int64

heingt
False    294
Name: heingt, dtype: int64

curb
False    294
Name: curb, dtype: int64

engineType
False    294
Name: engineType, dtype: int64

Cylinders
False    294
Name: Cylinders, dtype: int64

engine-size
False    294
Name: engine-size, dtype: int64

system
False    294
Name: system, dtype: int64

bore
False    294
Name: bore, dtype: int64

stroke
False    294
Name: stroke, dtype: int64

compression
False    294
Name: compression, dtype: int64

horsepower
False    294
Name: horsepower, dtype: int64

peak
False    294
Name: peak, dtype: int64

City
False    294
Name: City, dtype: int64

Higway
False    294
Name: Higway, dtype: int64

price
False    294
Name: price, dtype: int64

<h5 style="color: #008B8B">Eliminar filas faltantes</h5>

In [ ]:
# No elimar más del 5%

In [ ]:
#df_autos.dropnan("price"),axis=0 inplace=True
df_autos

In [41]:
#Cunando tengo indices repetidos o salteados se debe de reiniciar los indices.
df_autos.reset_index(drop=True, inplace=True)
df_autos

,symboling,normalized,make,fuel,aspiration,doors,style,wheels,engine,base,...,engine-size,system,bore,stroke,compression,horsepower,peak,City,Higway,price
0,0,106,nissan,gas,std,four,sedan,fwd,front,97.2,...,120,2bbl,3.33,3.47,8.5,97,5200,27,34,9549
1,0,128,nissan,gas,std,four,sedan,fwd,front,100.4,...,181,mpfi,3.43,3.27,9.0,152,5200,17,22,13499
2,0,108,nissan,gas,std,four,wagon,fwd,front,100.4,...,181,mpfi,3.43,3.27,9.0,152,5200,17,22,14399
3,0,108,nissan,gas,std,four,sedan,fwd,front,100.4,...,181,mpfi,3.43,3.27,9.0,152,5200,19,25,13499
4,3,194,nissan,gas,std,two,hatchback,rwd,front,91.3,...,181,mpfi,3.43,3.27,9.0,160,5200,19,25,17199
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
289,0,122,volkswagen,diesel,turbo,four,sedan,fwd,front,100.4,...,97,idi,3.01,3.40,23.0,68,4500,33,38,13845
290,0,122,volkswagen,gas,std,four,wagon,fwd,front,100.4,...,109,mpfi,3.19,3.40,9.0,88,5500,25,31,12290
291,-2,103,volvo,gas,std,four,sedan,rwd,front,104.3,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,12940
292,-1,74,volvo,gas,std,four,wagon,rwd,front,104.3,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,13415
293,-2,103,volvo,gas,std,four,sedan,rwd,front,104.3,...,141,mpfi,3.78,3.15,9.5,114,5400,24,28,15985